name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push Docker images (backend)
        uses: docker/build-push-action@v2
        with:
          context: back-end
          file: back-end/Dockerfile
          platforms: linux/amd64
          push: true
          tags: gcr.io/ta-allocation-382919/mybackend:latest

      - name: Remove backend import from Data-Form.js
        run: |
          sed -i 's/import semesterDataList from "..\/..\/..\/back-end\/main_pipeline\/semester_list.json";//g' front-end/react/pages/Data-Form.js

      - name: Build and push Docker images (frontend)
        uses: docker/build-push-action@v2
        with:
          context: front-end/react
          file: front-end/react/Dockerfile
          platforms: linux/amd64
          push: true
          tags: gcr.io/ta-allocation-382919/myfrontend:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCR_JSON_KEY }}
          project_id: ta-allocation-382919
          export_default_credentials: true

      - name: Configure gcloud CLI
        run: |
          gcloud config set project ta-allocation-382919
          gcloud container clusters get-credentials autopilot-cluster-1 --zone us-central1

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Apply dummy workload
        run: kubectl apply -f kubernetes/dummy-workload.yaml

      - name: Deploy to Google Kubernetes Engine
        run: |
          kubectl set image deployment/backend backend=gcr.io/ta-allocation-382919/mybackend:latest
          kubectl set image deployment/frontend frontend=gcr.io/ta-allocation-382919/myfrontend:latest

