name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: back-end
        file: back-end/Dockerfile
        platforms: linux/amd64
        push: true
        tags: gcr.io/ta-allocation-382919/mybackend:latest

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: front-end/react
        file: front-end/react/Dockerfile
        platforms: linux/amd64
        push: true
        tags: gcr.io/ta-allocation-382919/myfrontend:latest

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 363.0.0'

    - name: Install and configure gcloud CLI
      run: |
        VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        echo "${{ secrets.GCR_JSON_KEY }}" > gcp-key.json
        gcloud auth activate-service-account --key-file gcp-key.json
        gcloud config set project ta-allocation-382919
        gcloud container clusters get-credentials autopilot-cluster-1 --zone us-central1

    - name: Deploy to Google Kubernetes Engine
      run: |
        kubectl set image deployment/backend backend=gcr.io/ta-allocation-382919/mybackend:latest
        kubectl set image deployment/frontend frontend=gcr.io/ta-allocation-382919/myfrontend:latest

